### ISSUE TITLE
WBNB

### ISSUE THREAD

**Issue by RasyidMMJ** [RasyidMMJ/WBNB#2]
CAN"T NOT TRANSACTION TRUSTWALLET "SEND", "RECEIVE", "BUY", "SELL"
WBNB "1,708.170624" ADDRESS "0x84811d901063391658ddaCb6Dbc6926d9014038D"

**Comment by UserGithub005** [comment]
**PLEASE,,,,UPDATED YOUR ADDRESS WALLET**

~Miniature couscous.

**Comment by UserGithub005** [comment]
Hallo RasyidMMJ. 
Please update you address wallet  03 January 2024


~Miniature couscous.

**Comment by RasyidMMJ** [comment]
MY  pdate your address wallet.

0x26988c5054ff1e2c37cf0874963c7da23f4415e8

**Comment by UserGithub005** [comment]
Dear RasyidMMJ
Copy link address wallet please 👇
0x26988c5054ff1e2c37cf0874963c7da23f4415e8



~Miniature couscous

**Comment by UserGithub005** [comment]
@RasyidMMJ Please send a link to your wallet address from the Big Exchange Onchain network, I'll wait today or the process will be cancelled. Please respond

~Miniature couscous
